### ISSUE TITLE
git-issues responds badly to uninitialized repository

### ISSUE THREAD

**Issue by larsks** [duplys/git-issues#15]
Running `git issues list` before initializing a repository for git-issues results in Python traceback and `git` errors:

```
Traceback (most recent call last):
  File "/Users/lars/bin/git-issues", line 1061, in <module>
    issueSet = GitIssueSet().load_state()
  File "/Users/lars/bin/git-issues", line 412, in load_state
    cachedIssueSet = cPickle.load(fd)
  File "/Users/lars/bin/gitshelve.py", line 556, in __setstate__
    if not self.head or self.head != self.current_head():
  File "/Users/lars/bin/gitshelve.py", line 223, in current_head
    x = self.git('rev-parse', self.branch)
  File "/Users/lars/bin/gitshelve.py", line 220, in git
    return apply(git, args, kwargs)
  File "/Users/lars/bin/gitshelve.py", line 134, in git
    raise GitError(cmd, args, kwargs, err)
gitshelve.GitError: Git command failed: git rev-parse (): fatal: ambiguous argument 'issues': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It would be friendly to catch this particular situation and give the
user a help error message ("you need to run git issues init before
using this command") or something.

**Comment by larsks** [comment]
Apparently I'm lying and there was something else going on.
