### ISSUE TITLE
git mktree error on Windows

### ISSUE THREAD

**Issue by 501st-alpha1** [duplys/git-issues#25]
I tried creating a new issue with `git issues new "Some issue"`, and I got this error:

```
Traceback (most recent call last):
  File "[snip]\git-issues\git-issues", line 1243, in <module>
    issueSet.save_state()
  File "[snip]\git-issues\git-issues", line 438, in save_state
    self.shelf.sync()
  File "[snip]\git-issues\gitshelve.py", line 375, in sync
    self.commit()
  File "[snip]\git-issues\gitshelve.py", line 366, in commit
    tree = self.make_tree(self.objects, accumulator)
  File "[snip]\git-issues\gitshelve.py", line 338, in make_tree
    name = self.git('mktree', '-z', input=buf.getvalue())
  File "[snip]\git-issues\gitshelve.py", line 220, in git
    return apply(git, args, kwargs)
  File "[snip]\git-issues\gitshelve.py", line 134, in git
    raise GitError(cmd, args, kwargs, err)
gitshelve.GitError: Git command failed: git mktree (): fatal: path cb/4266b0c28c331fc69965b47242094468bd6f32/issue.xml contains slash
```

I'm running Windows 10, with Python 2.7.13.  I got no such error when running Debian 8 with Python 2.7.9.

**Comment by kevinanthonypamisetti** [comment]
The error:

```text
fatal: path cb/4266b0c28c331fc69965b47242094468bd6f32/issue.xml contains slash
```

comes from `git mktree`, not directly from Windows itself.

### What's happening?

`git mktree` expects tree entries to contain only a filename at the current tree level. The path being passed:

```text
cb/4266b0c28c331fc69965b47242094468bd6f32/issue.xml
```

contains `/` separators, which makes it a nested path. `git mktree` rejects such entries and reports:

```text
contains slash
```

This usually indicates a bug in the application generating the tree (in this case `git-issues` / `gitshelve`), where it is feeding full paths into `git mktree` instead of creating subtrees correctly.

### Why it often appears on Windows

Older versions of Git for Windows were stricter about path handling and tree creation. A bug that might go unnoticed on Linux can surface on Windows because of differences in Git versions and path normalization. Similar path-related issues are commonly reported when repositories contain path names that Windows or Git for Windows handles differently. ([[Reddit](https://www.reddit.com/r/git/comments/vjkvdu/how_to_resolve_filename_in_tree_entry_contains/?utm_source=chatgpt.com)][1])

### Things to try

1. Check your Git version:

```bash
git --version
```

2. Upgrade to the latest Git for Windows.

3. If you're maintaining `git-issues`, inspect the code around:

```python
self.git('mktree', '-z', input=buf.getvalue())
```

and verify that tree entries passed to `git mktree` contain only filenames, with nested directories represented as separate tree objects.

4. Test the same repository under:

   * WSL
   * Linux
   * a newer Git installation

to determine whether it's a Git-for-Windows compatibility issue or a bug in `git-issues`.

### Most likely root cause

This looks like an application bug in `git-issues` rather than a Windows configuration problem. The tool is attempting to create a Git tree entry whose name contains path separators, and `git mktree` refuses it.

[1]: https://www.reddit.com/r/git/comments/vjkvdu/how_to_resolve_filename_in_tree_entry_contains/?utm_source=chatgpt.com "\" filename in tree entry contains backslash\" error? : r/git"
